#version: '3.1'
#네트웍 브릿지 추가 함 

services:
  mariadb:
    container_name: devops-mariadb
    image: mariadb:10
    restart: always
    ports:
      - 3306:3306
    volumes:
      - shared-data:/var/lib/mysql:rw
    user: mysql
    environment:
      MARIADB_DATABASE: koreatech_db
      MARIADB_USER: koreatech
      MARIADB_PASSWORD: 1004koreatech
      MARIADB_ROOT_PASSWORD: 1004koreatech
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    networks:
      - my_bridge_network

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: devops-redis
    networks:
      - my_bridge_network

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - redis
      - mariadb
      - app1
      - app2
    networks:
      - my_bridge_network

  app1:
    image: masungil/devops:latest
    container_name: devops-app1
    networks:
      - my_bridge_network

  app2:
    image: masungil/devops:latest
    container_name: devops-app2
    networks:
      - my_bridge_network


networks:
  my_bridge_network:
    driver: bridge

volumes:
  shared-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db_data

